name: CI

on:
  push:
    tags:
      - '*'
    branches:
      - master
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.16.1

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            ~/.mix
            deps
            _build
          key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}

      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile
          mix dialyzer --plt

      - name: Compile
        env:
          MIX_ENV: test
        run: mix compile --warnings-as-errors

      - name: Lint format
        run: mix format --check-formatted

      - name: Lint dialyzer
        run: mix dialyzer --no-check

      - name: Lint credo
        run: mix credo --all --strict

      - name: Test
        run: mix coveralls.github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POSTGRES_HOST: postgres
